module.exports = {
    venom_seq : {
        name: "Naja nivea VenomSeq expression data",
        venomkb_id: "Q0000001",
        species_ref: "S8123548",
        dosage: 0.0086132,
        cell_line: "IMR-32",
        times_exposed: [
            6,
            24,
            36
        ],
        genes_up: [
            'CHGA',
            'MYL12B',
            'CLDND1',
            'COPG1',
            'PFDN2',
            'WARS',
            'CWF19L2',
            'PDLIM7',
            'SH3BGRL3',
            'ARPC5L',
            'RHOA',
            'NFYC',
            'ZYX',
            'NEFH',
            'HERC2',
            'MAGT1',
            'CPT1A',
            'CEP95',
            'MLX',
            'ASPH',
            'NUP188',
            'HSPA5',
            'MTA2',
            'ASS1',
            'CBFB',
            'TP53I11',
            'RIMKLB',
            'CREG1',
            'PCYOX1L',
            'SLC10A3',
            'DPYSL2',
            'ZNF557',
            'EIF1AD',
            'TACC1',
            'ACBD3',
            'BRD9',
            'MAPK8IP1',
            'MYNN',
            'CEP135',
            'SCG2',
            'LRP10',
            'BIVM',
            'PMAIP1',
            'IFITM2',
            'NQO1',
            'HLA-DRB1',
            'ZNF569',
            'HLA-B',
            'SPRED2',
            'PLEK',
            'KCNT2',
            'HLA-DQB1',
            'ANXA11',
            'TUBA1C',
            'FAM114A1',
            'CSAG1',
            'DDIT3',
            'CYGB',
            'LCP1',
            'MT2A',
            'CLDN7',
            'S100A11',
            'ISLR',
            'TM9SF1',
            'PRAC1',
            'S100A10',
            'CSRP1',
            'KLK4',
            'TNFRSF12A',
            'MAL2',
            'ELL',
            'HLA-C',
            'TDRD3',
            'CEACAM6',
            'TMED2',
            'SPRY4',
            'MGST2',
            'MVK',
            'LENG9',
            'VAMP8',
            'ZNF391',
            'SELL',
            'SYT2',
            'TRIP6',
            'PRKCB',
            'DGAT1',
            'TM4SF1',
            'CPNE8',
            'CAV1',
            'MLPH',
            'STRA6',
            'KIAA0040',
            'KLHL36',
            'TGM2',
            'LAMA3',
            'PASD1',
            'ADGRG6',
            'TMC4',
            'DYRK4',
            'STK32B',
            'MICB',
            'TSPAN8'
        ],
        genes_down: [
            'LRRTM2',
            'RPRM',
            'FAM117B',
            'ESPL1',
            'ELN',
            'CENPA',
            'DDT',
            'DPM3',
            'GFM1',
            'TIAM2',
            'NEUROD1',
            'GKAP1',
            'MAPKAPK5-AS1',
            'MUT',
            'C14orf132',
            'CCNG1',
            'C4orf46',
            'CLVS2',
            'UQCRFS1',
            'NCL',
            'RBPJ',
            'ARID2',
            'NBAS',
            'SLC25A3',
            'NOLC1',
            'LDHB'
        ],
        raw_data: "http://foo.bar/v1.csv.zip",
        out_links: []
    },
    species_link: {
        "lastUpdated": 1530210365719,
        "name": "Naja nivea",
        "out_links": {
            "ncbi_taxonomy": {
                "id": "8655"
            }
        },
        "common_name": "Cape cobra",
        "venomkb_id": "S8123548",
        "venom_ref": "V8123548",
        "venom": {
            "proteins": [
                "P6395789",
            ],
            "name": "Naja nivea venom"
        },
        "species_image_url": "https://upload.wikimedia.org/wikipedia/commons/d/d5/Naja_nivea_IMG_5078_Kappkobra.jpg",
        "annotation_score": 4
    },
    protein_linked: {
        "lastUpdated": 1530210450207,
        "description": "Binds with low affinity to muscular (alpha-1-beta-1-epsilon-delta/CHRNA1-CHRNB1-CHRNE-CHRND) and very low affinity to neuronal (alpha7) nicotinic acetylcholine receptor (nAChR).",
        "aa_sequence": "LRCLNCPEVFCRNFHTCRNGEKICFKRFDQRKLLGKRYTRGCAVTCPVAKPREIVECCSTDGCNR",
        "venomkb_id": "P6395789",
        "venom_ref": "V8123548",
        "name": "Weak toxin CM-10",
        "pdb_image_url": "http://www.rcsb.org/pdb/images/2MJ0_bio_r_250.jpg",
        "pdb_structure_known": false,
        "annotation_score": 3,
    }
}