module.exports = {
    genome_test: {
        "lastUpdated": 1528312461802,
        "assembly_platform": "",
        "annotation_score": 4,
        "name": "Apis mellifera complete genome",
        "project_homepage": "",
        "literature_reference": {
            "pmid": "17073008",
            "authors": [
                "Weinstock GM",
                "Robinson GE",
                "Gibbs RA",
                "Weinstock GM",
                "Robinson GE",
                "Worley KC",
                "Evans JD",
                "Maleszka R",
                "Robertson HM",
                "Weaver DB",
                "Beye M",
                "Bork P",
                "Elsik CG",
                "Evans JD",
                "Hartfelder K",
                "Hunt GJ",
                "Robertson HM",
                "Robinson GE",
                "Maleszka R",
                "Weinstock GM",
                "Worley KC",
                "Zdobnov EM",
                "Hartfelder K",
                "Amdam GV",
                "Bitondi MM",
                "Collins AM",
                "Cristino AS",
                "Evans JD",
                "Lattorff MG",
                "Lobo CH",
                "Moritz RF",
                "Nunes FM",
                "Page RE Jr",
                "Simoes ZL",
                "Wheeler D",
                "Carninci P",
                "Fukuda S",
                "Hayashizaki Y",
                "Kai C",
                "Kawai J",
                "Sakazume N",
                "Sasaki D",
                "Tagami M",
                "Maleszka R",
                "Amdam GV",
                "Albert S",
                "Baggerman G",
                "Beggs KT",
                "Bloch G",
                "Cazzamali G",
                "Cohen M",
                "Drapeau MD",
                "Eisenhardt D",
                "Emore C",
                "Ewing MA",
                "Fahrbach SE",
                "Foret S",
                "Grimmelikhuijzen CJ",
                "Hauser F",
                "Hummon AB",
                "Hunt GJ",
                "Huybrechts J",
                "Jones AK",
                "Kadowaki T",
                "Kaplan N",
                "Kucharski R",
                "Leboulle G",
                "Linial M",
                "Littleton JT",
                "Mercer AR",
                "Page RE Jr",
                "Robertson HM",
                "Robinson GE",
                "Richmond TA",
                "Rodriguez-Zas SL",
                "Rubin EB",
                "Sattelle DB",
                "Schlipalius D",
                "Schoofs L",
                "Shemesh Y",
                "Sweedler JV",
                "Velarde R",
                "Verleyen P",
                "Vierstraete E",
                "Williamson MR",
                "Beye M",
                "Ament SA",
                "Brown SJ",
                "Corona M",
                "Dearden PK",
                "Dunn WA",
                "Elekonich MM",
                "Elsik CG",
                "Foret S",
                "Fujiyuki T",
                "Gattermeier E",
                "Gempe T",
                "Hasselmann M",
                "Kadowaki T",
                "Kage E",
                "Kamikouchi A",
                "Kubo T",
                "Kucharski R",
                "Kunieda T",
                "Lorenzen M",
                "Maleszka R",
                "Milshina NV",
                "Morioka M",
                "Ohashi K",
                "Overbeek R",
                "Page RE Jr",
                "Robertson HM",
                "Robinson GE",
                "Ross CA",
                "Schioett M",
                "Shippy T",
                "Takeuchi H",
                "Toth AL",
                "Willis JH",
                "Wilson MJ",
                "Robertson HM",
                "Zdobnov EM",
                "Bork P",
                "Elsik CG",
                "Gordon KH",
                "Letunic I",
                "Hackett K",
                "Peterson J",
                "Felsenfeld A",
                "Guyer M",
                "Solignac M",
                "Agarwala R",
                "Cornuet JM",
                "Elsik CG",
                "Emore C",
                "Hunt GJ",
                "Monnerot M",
                "Mougel F",
                "Reese JT",
                "Schlipalius D",
                "Vautrin D",
                "Weaver DB",
                "Gillespie JJ",
                "Cannone JJ",
                "Gutell RR",
                "Johnston JS",
                "Elsik CG",
                "Cazzamali G",
                "Eisen MB",
                "Grimmelikhuijzen CJ",
                "Hauser F",
                "Hummon AB",
                "Iyer VN",
                "Iyer V",
                "Kosarev P",
                "Mackey AJ",
                "Maleszka R",
                "Reese JT",
                "Richmond TA",
                "Robertson HM",
                "Solovyev V",
                "Souvorov A",
                "Sweedler JV",
                "Weinstock GM",
                "Willliamson MR",
                "Zdobnov EM",
                "Evans JD",
                "Aronstein KA",
                "Bilikova K",
                "Chen YP",
                "Clark AG",
                "Decanini LI",
                "Gelbart WM",
                "Hetru C",
                "Hultmark D",
                "Imler JL",
                "Jiang H",
                "Kanost M",
                "Kimura K",
                "Lazzaro BP",
                "Lopez DL",
                "Simuth J",
                "Thompson GJ",
                "Zou Z",
                "De Jong P",
                "Sodergren E",
                "Csuros M",
                "Milosavljevic A",
                "Johnston JS",
                "Osoegawa K",
                "Richards S",
                "Shu CL",
                "Weinstock GM",
                "Elsik CG",
                "Duret L",
                "Elhaik E",
                "Graur D",
                "Reese JT",
                "Robertson HM",
                "Robertson HM",
                "Elsik CG",
                "Maleszka R",
                "Weaver DB",
                "Amdam GV",
                "Anzola JM",
                "Campbell KS",
                "Childs KL",
                "Collinge D",
                "Crosby MA",
                "Dickens CM",
                "Elsik CG",
                "Gordon KH",
                "Grametes LS",
                "Grozinger CM",
                "Jones PL",
                "Jorda M",
                "Ling X",
                "Matthews BB",
                "Miller J",
                "Milshina NV",
                "Mizzen C",
                "Peinado MA",
                "Reese JT",
                "Reid JG",
                "Robertson HM",
                "Robinson GE",
                "Russo SM",
                "Schroeder AJ",
                "St Pierre SE",
                "Wang Y",
                "Zhou P",
                "Robertson HM",
                "Agarwala R",
                "Elsik CG",
                "Milshina NV",
                "Reese JT",
                "Weaver DB",
                "Worley KC",
                "Childs KL",
                "Dickens CM",
                "Elsik CG",
                "Gelbart WM",
                "Jiang H",
                "Kitts P",
                "Milshina NV",
                "Reese JT",
                "Ruef B",
                "Russo SM",
                "Venkatraman A",
                "Weinstock GM",
                "Zhang L",
                "Zhou P",
                "Johnston JS",
                "Aquino-Perez G",
                "Cornuet JM",
                "Monnerot M",
                "Solignac M",
                "Vautrin D",
                "Whitfield CW",
                "Behura S",
                "Berlocher SH",
                "Clark AG",
                "Gibbs RA",
                "Johnston JS",
                "Sheppard WS",
                "Smith DR",
                "Suarez AV",
                "Tsutsui ND",
                "Weaver DB",
                "Wei X",
                "Wheeler D",
                "Weinstock GM",
                "Worley KC",
                "Havlak P",
                "Li B",
                "Liu Y",
                "Sodergren E",
                "Zhang L",
                "Beye M",
                "Hasselmann M",
                "Jolivet A",
                "Lee S",
                "Nazareth LV",
                "Pu LL",
                "Thorn R",
                "Weinstock GM",
                "Stolc V",
                "Robinson GE",
                "Maleszka R",
                "Newman T",
                "Samanta M",
                "Tongprasit WA",
                "Aronstein KA",
                "Claudianos C",
                "Berenbaum MR",
                "Biswas S",
                "de Graaf DC",
                "Feyereisen R",
                "Johnson RM",
                "Oakeshott JG",
                "Ranson H",
                "Schuler MA",
                "Muzny D",
                "Gibbs RA",
                "Weinstock GM",
                "Chacko J",
                "Davis C",
                "Dinh H",
                "Gill R",
                "Hernandez J",
                "Hines S",
                "Hume J",
                "Jackson L",
                "Kovar C",
                "Lewis L",
                "Miner G",
                "Morgan M",
                "Nazareth LV",
                "Nguyen N",
                "Okwuonu G",
                "Paul H",
                "Richards S",
                "Santibanez J",
                "Savery G",
                "Sodergren E",
                "Svatek A",
                "Villasana D",
                "Wright R"
            ],
            "citation": "Nature. 2006 Oct 26;443(7114):931-49.",
            "journal": "Nature",
            "title": "Insights into social insects from the genome of the honeybee Apis mellifera."
        },
        "venomkb_id": "G3863526",
        "out_links": [{
            "resource": "ncbi_genome",
            "primary_id" : 48,
            "attribute": "https://www.ncbi.nlm.nih.gov/genome/48",
            "shared": false,
        }],
        "species_ref": "S4876300"
    }, species_linked: {
        "lastUpdated": 1528318675314,
        "name": "Apis mellifera",
        "common_name": "Honeybee",
        "venomkb_id": "S4876300",
        "venom_ref": "V4876300",
        "venom": {
            "proteins": [
                "P6912376",
            ],
            "name": "Apis mellifera venom"
        },

        "species_image_url": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Apis_mellifera_Tanzania.jpg",
        "annotation_score": 4
    }, protein_linked: {
        "lastUpdated": 1528318955677,
        "description": null,
        "aa_sequence": "MSVIAILAMVVGVQAELKQINVIFRHGDRIPDEKNEMYPKDPYLYYDFYPLERGELTNSGKMREYQLGQFLRERYGDFLGDIYTEESVSALSSFYDRTKMSLQLVLAALYPPNKLQQWNEDLNWQPIATKYLRRYEDNIFLPEDCLLFTIELDRVLESPRGKYEFSKYDKLKKKLEEWTGKNITTPWDYYYIYHTLVAEQSYGLTLPSWTNNIFPRGELFDATVFTYNITNSTPLLKKLYGGPLLRIFTKHMLDVVSGTQKKKRKIYLFSGHESNIASVLHALQLYYPHVPEYSSSIIMELHNIEGTHYVKIVYYLGIPSEARELQLPGCEVLCPLYKYLQLIENVIPSNEELICDKRFVDESANNLSIEELDFVKLNLIRIAGTENK",
        "venomkb_id": "P6912376",
        "venom_ref": "V4876300",
        "name": "Venom acid phosphatase Acph-1",
        "pdb_image_url": "http://www.rcsb.org/pdb/images/1RPT_bio_r_250.jpg",
        "pdb_structure_known": false,
        "literature_predications": [
                {
                    "o_name": "Hypersensitivity",
                    "predicate": "TREATS",
                    "o_type": "patf",
                    "id_pred": "bVjy5ovpRMSMo0LwbDKtCA==",
                    "PID": 2618869,
                    "s_type": "medd",
                    "o_cui": "C0020517",
                    "s_name": "Diagnostic test device",
                    "SID": 86197840,
                    "vkb_protein_ref": "P6912376",
                    "pmid": 16630944,
                    "toxprot_id": "Q5BLY5",
                    "PMID": 16630944,
                    "s_cui": "C1263440"
                }
        ],

        "annotation_score": 5,
    },
    g_without_lastupdated: {
        "assembly_platform": "",
        "annotation_score": 3,
        "name": "Conus bullatus complete genome",
        "project_homepage": "",
        "literature_reference": {
            "pmid": "21266071",
            "authors": [
                "Hu H",
                "Bandyopadhyay PK",
                "Olivera BM",
                "Yandell M"
            ],
            "citation": "BMC Genomics. 2011 Jan 25;12:60. doi: 10.1186/1471-2164-12-60.",
            "journal": "BMC genomics",
            "title": "Characterization of the Conus bullatus genome and its venom-duct transcriptome."
        },
        "venomkb_id": "G3307719",
        "out_links": [{
            "resource": "ncbi_genome",
            "primary_id": 10842,
            "attribute": "https://www.ncbi.nlm.nih.gov/genome/10482",
            "shared": false,
        }],
        "species_ref": "S6678150"
    }, g_without_name: {
        "lastUpdated": 1528314802041,
        "assembly_platform": "",
        "annotation_score": 3,
        "project_homepage": "",
        "literature_reference": {
            "pmid": "21266071",
            "authors": [
                "Hu H",
                "Bandyopadhyay PK",
                "Olivera BM",
                "Yandell M"
            ],
            "citation": "BMC Genomics. 2011 Jan 25;12:60. doi: 10.1186/1471-2164-12-60.",
            "journal": "BMC genomics",
            "title": "Characterization of the Conus bullatus genome and its venom-duct transcriptome."
        },
        "venomkb_id": "G3307719",
        "out_links": [{
            "resource": "ncbi_genome",
            "primary_id": 10842,
            "attribute": "https://www.ncbi.nlm.nih.gov/genome/10482",
            "shared": false,
        }],
        "species_ref": "S6678150"
    }, g_without_venomkb_id: {
        "lastUpdated": 1528314802041,
        "assembly_platform": "",
        "annotation_score": 3,
        "name": "Conus bullatus complete genome",
        "project_homepage": "",
        "literature_reference": {
            "pmid": "21266071",
            "authors": [
                "Hu H",
                "Bandyopadhyay PK",
                "Olivera BM",
                "Yandell M"
            ],
            "citation": "BMC Genomics. 2011 Jan 25;12:60. doi: 10.1186/1471-2164-12-60.",
            "journal": "BMC genomics",
            "title": "Characterization of the Conus bullatus genome and its venom-duct transcriptome."
        },
        "out_links": [{
            "resource": "ncbi_genome",
            "primary_id": 10842,
            "attribute": "https://www.ncbi.nlm.nih.gov/genome/10482",
            "shared": false,
        }],
        "species_ref": "S6678150"
    }, g_without_score_annotation: {
        "lastUpdated": 1528314802041,
        "assembly_platform": "",
        "name": "Conus bullatus complete genome",
        "project_homepage": "",
        "literature_reference": {
            "pmid": "21266071",
            "authors": [
                "Hu H",
                "Bandyopadhyay PK",
                "Olivera BM",
                "Yandell M"
            ],
            "citation": "BMC Genomics. 2011 Jan 25;12:60. doi: 10.1186/1471-2164-12-60.",
            "journal": "BMC genomics",
            "title": "Characterization of the Conus bullatus genome and its venom-duct transcriptome."
        },
        "venomkb_id": "G3307719",
        "out_links": [{
            "resource": "ncbi_genome",
            "primary_id": 10842,
            "attribute": "https://www.ncbi.nlm.nih.gov/genome/10482",
            "shared": false,
        }],
        "species_ref": "S6678150"
    }, genome_venomkb_id: {
        "lastUpdated": 1528314802041,
        "assembly_platform": "",
        "annotation_score": 3,
        "name": "Conus bullatus complete genome",
        "project_homepage": "",
        "literature_reference": {
            "pmid": "21266071",
            "authors": [
                "Hu H",
                "Bandyopadhyay PK",
                "Olivera BM",
                "Yandell M"
            ],
            "citation": "BMC Genomics. 2011 Jan 25;12:60. doi: 10.1186/1471-2164-12-60.",
            "journal": "BMC genomics",
            "title": "Characterization of the Conus bullatus genome and its venom-duct transcriptome."
        },
        "venomkb_id": "G3863526",
        "out_links": {
            "ncbi_genome": {
                "link": "https://www.ncbi.nlm.nih.gov/genome/10842",
                "id": 10842
            }
        },
        "species_ref": "S6678150"
    }


}